### ISSUE TITLE
Getting Started: Developer Accounts?

### ISSUE THREAD

**Issue by Dog** [mint-labs/mintAPI#3]
I wanted to try out the API and play with the code, but it isn't clear to me how I should go about doing that. I see that I can make an account, but I'm neither a patient or specialist. I'm also worried about the possibility of having to spend credits to test code.

How do I get started as a developer?

**Comment by alvaroabascar** [comment]
Hi Dog! The platform is now devised to analyse MRI data, so basically you can create patients, upload MRI data and start an analysis. We have created this API to easily create and upload data of many subjects. You can play with it and it wont consume credits as long as you don't start analysis.

However we have to keep introducing changes to adapt it to the changes in the platform, so you might find some piece of code which stops working.

Cheers,
Álvaro

**Comment by Dog** [comment]
Thanks, I'm waiting for administrator approval of my account now.

I've noticed when the username is not long enough, the registration page incorrectly tells the user they are using invalid characters. The username `dog` seems to trigger this, and is reproducible.

**Comment by merqurio** [comment]
I'll ask him to approve you, thanks for the username tip BTW , I'll let the web developer know about it :grin:
